# Generated by Django 4.2 on 2026-02-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='property/default.jpg', upload_to='property/')),
                ('image2', models.ImageField(default='property/default.jpg', upload_to='property/')),
                ('image3', models.ImageField(default='property/default.jpg', upload_to='property/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.TextField(blank=True, null=True)),
                ('floor', models.ImageField(default='property/default.jpg', upload_to='property/')),
                ('map', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root.agent')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.propertytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
